#!/bin/bash
alias ls='ls -GF'
  # -G, --no-group             in a long listing, don't print group names
  # -F, --classify             append indicator (one of */=>@|) to entries
alias ll='ls -hlGFa'
  # -h, --human-readable       with -l and/or -s, print human readable sizes
  # -a, --all                  do not ignore entries starting with .
  # -G, --no-group             in a long listing, don't print group names
  # -F, --classify             append indicator (one of */=>@|) to entries
  # -a, --all                  do not ignore entries starting with .
