#!/bin/bash
_symfony_console () {
  find ./{app,bin} -maxdepth 2 -mindepth 1 -name 'console' -type f 2>/dev/null | head -n 1
}
alias sf='echo $BLUE $(_symfony_console) && `_symfony_console`'
alias sc='sf'
alias sccc='echo "$BLUE sc cache:clear $NORMAL" && sc cache:clear'
alias sccw='echo "$BLUE sccc --no-warmup $NORMAL" && sccc --no-warmup'
alias scdfl='echo "$BLUE sc doctrine:fixtures:load $NORMAL" && sc doctrine:fixtures:load'
alias scdfl-force='echo "$BLUE sc doctrine:database:drop --force && sc doctrine:database:create && sc doctrine:schema:update --force && sc hautelook_alice:doctrine:fixtures:load --no-interaction && sc doctrine:fixtures:load --append --no-interaction $NORMAL" && sc doctrine:database:drop --force && sc doctrine:database:create && sc doctrine:schema:update --force && sc hautelook_alice:doctrine:fixtures:load --no-interaction && sc doctrine:fixtures:load --append --no-interaction'
alias scdsu='echo "$BLUE sc doctrine:schema:update $NORMAL" && sc doctrine:schema:update'
alias scdsuf='echo "$BLUE sc doctrine:schema:update --force $NORMAL" && sc doctrine:schema:update --force'
alias scdge='echo "$BLUE sc doctrine:generate:entities $NORMAL" && sc doctrine:generate:entities'
alias scdgr='echo "$BLUE sc debug:router $NORMAL" && sc debug:router'
alias scdgt='echo "$BLUE sc debug:translation $NORMAL" && sc debug:translation'
