#!/bin/bash
# Should lesspipe be installed; use it.
# Linux users' LESS should allow it without additional software.
# OSX users are less lucky.
# $ brew install lesspipe
# Why?
# * Because it allows you to show the contents of zip files.
BINLESSPIPE="lesspipe.sh"
BINBREW="brew"
if [[ $(command -v $BINLESSPIPE) == "" ]]; then
  echo "/!\ $BINLESSPIPE not installed.."
  if [[ $(command -v $BINBREW) == "" ]]; then
    echo "Install it using brew:"
    echo "\$ brew install lesspipe"
  fi
else
  export LESSOPEN="|/usr/local/bin/lesspipe.sh %s" LESS_ADVANCED_PREPROCESSOR=1
fi
