#!/bin/bash
GIT_PROMPT_ONLY_IN_REPO=1
# @deprecated: this is a bit much for my taste
# source $HOME/.bash/lib/magicmonty/bash-git-prompt/gitprompt.sh
if [ -f "${PATH_GIT_PROMPT}" ]; then
  source "${PATH_GIT_PROMPT}"
fi
# Last part of current working directory and the git branch we're in.
# Thanks @janmoesen for pointing me to the \[\] surrounding the non-printing
# chars.  These are necessary to prevent issues with command line editing,
# -browsing, -completion.
if __git_ps1 2>/dev/null; then
  PROMPT_COMMAND='__git_ps1 "\[${REVERSE}\]\[${BLUE}\] \t \[${NORMAL}\]\[${BLUE}\] \W\[${NORMAL}\]" " "'
fi
