#!/bin/bash
GIT_PROMPT_ONLY_IN_REPO=1
# @deprecated: this is a bit much for my taste
# source $HOME/.bash/lib/magicmonty/bash-git-prompt/gitprompt.sh
source "$PATH_GIT_PROMPT"
# Last part of current working directory and the git branch we're in.
# Thanks @janmoesen for pointing me to the \[\] surrounding the non-printing
# chars.  These are necessary to prevent issues with command line editing,
# -browsing, -completion.
PROMPT_COMMAND='__git_ps1 "\[${REVERSE}\]\[${BLUE}\] \t \[${NORMAL}\]\[${BLUE}\] \W\[${NORMAL}\]" " "'
