#!/bin/bash
echo "* completion \"project\" ${DIR_ROOT_PROJECT_GOTO}"
complete -F __list_projects project_goto
__list_projects(){
  local cur=${COMP_WORDS[COMP_CWORD]}
  COMPREPLY=( $(compgen -W "$(ls ${DIR_ROOT_PROJECT_GOTO})" -- $cur) )
}
