#!/bin/bash
DIRECTORY=$1
DIR_TARGET="$DIR_ROOT_PROJECT_GOTO$DIRECTORY"
if [ -d "$DIR_TARGET" ]; then
  echo "$BLUE change dir to project '$DIR_TARGET' $NORMAL"
  cd "$DIR_TARGET"
else
  echo "$RED Dir '$DIR_TARGET' does not exist! Taking you to root instead. $NORMAL"
  cd $DIR_ROOT_PROJECT_GOTO
fi
