#!/bin/bash
# @todo: do a dry run by default?
# @todo: provide an option to insert --force option to git
#   to omit the "already exists in rev-list" warning.
usage="$appname [-h] <wrong email> <correct email> <name> -- Rewrite author for entire history.
where:
  -h | --help        Show usage help.
  wrong email        replace@this.email
  correct email      with@this.email
  name               SayMyName"
author=$(git config user.email)
wrong_author_email="$1"
correct_author_email="$2"
correct_author_name="$3"
if [[ "$wrong_author_email" == "" ]] \
  || [[ "$correct_author_email" == "" ]] \
  || [[ "$correct_author_name" == "" ]]
then
  echo "${usage}"
  exit 0
fi

YESNO="(y/N)"
echo "😳 Are you sure you want to rewrite history? ${YESNO}"
read decision
if [ "$decision" != "y" ]; then echo "Exiting. No changes made." && exit 1; fi

script="
WRONG_EMAIL=\"${wrong_author_email}\"
NEW_EMAIL=\"${correct_author_email}\"
NEW_NAME=\"${correct_author_name}\"
if [ \"\$GIT_COMMITTER_EMAIL\" = \"\$WRONG_EMAIL\" ]
then
  export GIT_COMMITTER_NAME=\"\$NEW_NAME\"
  export GIT_COMMITTER_EMAIL=\"\$NEW_EMAIL\"
fi
if [ \"\$GIT_AUTHOR_EMAIL\" = \"\$WRONG_EMAIL\" ]
then
  export GIT_AUTHOR_NAME=\"\$NEW_NAME\"
  export GIT_AUTHOR_EMAIL=\"\$NEW_EMAIL\"
fi
"
git filter-branch -f --env-filter "$script" --tag-name-filter cat -- --branches --tags
