#!/bin/bash
# Test a given ssh_config host identifier.
identifier=$1
ssh -o PasswordAuthentication=no "${identifier}" true \
  && { ${GREEN} ; echo "Success!"; } \
  || { ${RED} ; echo "Failure"; } \
  ; ${NORMAL}
