#!/bin/bash
# adds ~/.ssh/config to the ssh autocomplete
# Call whenever ssh host config changes (@see ssh_configure_host)
# @TODO: experiment with file listener to update autocomplete automatically
script_dir="${DIR_BASH}/ssh/ssh_config_autocomplete_load"
dir=${DIR_SSH}/{config,conf.d/*.conf}
if [ "$BASHCONFIGLOADERVERBOSITY" -gt "0" ]; then
  echo "* completion \"ssh_config\" ${dir}"
fi
if ! command -v awk >/dev/null
then
  echo "  /!\ awk is unavailable.  Aborting..(${script_dir})";
fi

if [[ -f "${DIR_SSH}/config" && -d "${DIR_SSH}/conf.d" && -f "${DIR_SSH}/conf.d/default.conf" ]]
then
  complete -W "$(awk '/^\s*Host\s*/ { sub(/^\s*Host /, ""); print; }' ${DIR_SSH}/{config,conf.d/*.conf})" ssh
else
  echo "  ${BRIGHT}${RED}/!\\${NORMAL} ssh directory structure is incompatible.  Aborting..(${script_dir})"
  echo "  expected tree:"
  echo "  $HOME/.ssh"
  echo "  |-- conf.d"
  echo "  |   \`-- default.conf"
  echo "  \`-- config"
fi
